#include <windows.h>
#include <windowsx.h>
#include <dwmapi.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <mutex>
#include <string>
#include <thread>
#include <vector>
using namespace std::chrono_literals;

namespace {
constexpr wchar_t kClassName[] = L"SNEWSWARE_WINDOW";
constexpr COLORREF BG=RGB(20,20,25), PANEL=RGB(26,27,34), CARD=RGB(14,15,21), TEXT=RGB(246,244,241), MUTED=RGB(151,145,148), ORANGE=RGB(255,105,35), RED=RGB(237,55,48), GREEN=RGB(45,205,117);
HWND g_hwnd{}; HHOOK g_hook{}; std::atomic_bool g_run{true}, g_socd{false}, g_fisher{false}, g_chest{false}, g_fishingActive{false};
std::atomic_int g_tab{0}; bool heldA=false,heldD=false; int activeKey=0; std::mutex keyMutex;

bool RobloxFocused(){ HWND w=GetForegroundWindow(); if(!w)return false; DWORD pid=0; GetWindowThreadProcessId(w,&pid); HANDLE h=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid); if(!h)return false; wchar_t p[1024]{}; DWORD n=1024; bool ok=QueryFullProcessImageNameW(h,0,p,&n); CloseHandle(h); if(!ok)return false; std::wstring s(p,n); std::transform(s.begin(),s.end(),s.begin(),::towlower); return s.find(L"robloxplayerbeta.exe")!=std::wstring::npos; }
void Key(int vk,bool down){ INPUT i{}; i.type=INPUT_KEYBOARD; i.ki.wVk=(WORD)vk; i.ki.dwExtraInfo=0x534E4557; if(!down)i.ki.dwFlags=KEYEVENTF_KEYUP; SendInput(1,&i,sizeof(i)); }
void MouseButton(bool down){INPUT i{};i.type=INPUT_MOUSE;i.mi.dwFlags=down?MOUSEEVENTF_LEFTDOWN:MOUSEEVENTF_LEFTUP;SendInput(1,&i,sizeof(i));}
void Click(int x,int y,bool down){ SetCursorPos(x,y); MouseButton(down); }
void ReleaseAutomation(){ if(activeKey){Key(activeKey,false);activeKey=0;} MouseButton(false); }
void Activate(int vk){ if(activeKey==vk)return; if(activeKey)Key(activeKey,false); activeKey=vk; if(vk)Key(vk,true); }

LRESULT CALLBACK KeyboardHook(int code,WPARAM wp,LPARAM lp){ if(code<0)return CallNextHookEx(g_hook,code,wp,lp); auto*k=(KBDLLHOOKSTRUCT*)lp; bool down=wp==WM_KEYDOWN||wp==WM_SYSKEYDOWN, up=wp==WM_KEYUP||wp==WM_SYSKEYUP;
 if(down&&k->vkCode=='Q'&&(GetAsyncKeyState(VK_CONTROL)&0x8000)){g_socd=false;g_fisher=false;g_chest=false;g_fishingActive=false;ReleaseAutomation();InvalidateRect(g_hwnd,nullptr,FALSE);return 1;}
 if(k->dwExtraInfo==0x534E4557)return CallNextHookEx(g_hook,code,wp,lp);
 if(!g_socd||!RobloxFocused()||(k->vkCode!='A'&&k->vkCode!='D'))return CallNextHookEx(g_hook,code,wp,lp);
 std::scoped_lock lock(keyMutex); if(k->vkCode=='A'){if(down){heldA=true;Activate('A');}if(up){heldA=false;Activate(heldD?'D':0);}} else {if(down){heldD=true;Activate('D');}if(up){heldD=false;Activate(heldA?'A':0);}} return 1; }

struct Shot{int w=0,h=0;std::vector<COLORREF> px; COLORREF at(int x,int y)const{return (x>=0&&y>=0&&x<w&&y<h)?px[(size_t)y*w+x]:0;}};
Shot Capture(){Shot s; RECT r{};GetWindowRect(GetForegroundWindow(),&r);s.w=r.right-r.left;s.h=r.bottom-r.top;if(s.w<1||s.h<1)return s;HDC sc=GetDC(nullptr),mem=CreateCompatibleDC(sc);HBITMAP b=CreateCompatibleBitmap(sc,s.w,s.h);auto old=SelectObject(mem,b);BitBlt(mem,0,0,s.w,s.h,sc,r.left,r.top,SRCCOPY);BITMAPINFO bi{};bi.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);bi.bmiHeader.biWidth=s.w;bi.bmiHeader.biHeight=-s.h;bi.bmiHeader.biPlanes=1;bi.bmiHeader.biBitCount=32;bi.bmiHeader.biCompression=BI_RGB;s.px.resize((size_t)s.w*s.h);GetDIBits(mem,b,0,s.h,s.px.data(),&bi,DIB_RGB_COLORS);SelectObject(mem,old);DeleteObject(b);DeleteDC(mem);ReleaseDC(nullptr,sc);return s;}
bool near(COLORREF c,int r,int g,int b,int d){return abs((int)GetRValue(c)-r)<d&&abs((int)GetGValue(c)-g)<d&&abs((int)GetBValue(c)-b)<d;}
struct Box{int l=0,t=0,r=0,b=0;int area()const{return std::max(0,r-l)*std::max(0,b-t);}};
Box ColorBounds(const Shot&s,bool(*match)(COLORREF)){Box b{s.w,s.h,0,0};int count=0;for(int y=s.h/3;y<s.h;y+=2)for(int x=0;x<s.w;x+=2)if(match(s.at(x,y))){b.l=std::min(b.l,x);b.r=std::max(b.r,x);b.t=std::min(b.t,y);b.b=std::max(b.b,y);count++;}if(count<20)return {};return b;}
bool Green(COLORREF c){return GetGValue(c)>145&&GetGValue(c)>GetRValue(c)*1.25&&GetGValue(c)>GetBValue(c)*1.05;}
bool Pink(COLORREF c){return GetRValue(c)>150&&GetBValue(c)>90&&GetRValue(c)>GetGValue(c)*1.25;}

void FisherLoop(){bool mouseDown=false;auto lastProbe=std::chrono::steady_clock::now()-1s,lastSeen=lastProbe;while(g_run){if(!g_fisher||!RobloxFocused()){if(mouseDown){MouseButton(false);mouseDown=false;}g_fishingActive=false;std::this_thread::sleep_for(50ms);continue;}auto now=std::chrono::steady_clock::now();auto wait=g_fishingActive?15ms:500ms;if(now-lastProbe<wait){std::this_thread::sleep_for(5ms);continue;}lastProbe=now;Shot s=Capture();Box green=ColorBounds(s,Green),pink=ColorBounds(s,Pink);bool found=green.area()>250&&pink.area()>50&&green.t>s.h/2;if(found){g_fishingActive=true;lastSeen=now;int gy=(green.t+green.b)/2,py=(pink.t+pink.b)/2;bool wantDown=gy>py+3;if(wantDown!=mouseDown){Click((green.l+green.r)/2,gy,wantDown);mouseDown=wantDown;}}else if(g_fishingActive&&now-lastSeen>200ms){if(mouseDown){MouseButton(false);mouseDown=false;}g_fishingActive=false;}InvalidateRect(g_hwnd,nullptr,FALSE);} }

bool DetectChest(const Shot&s,Box&grid){ // finds the characteristic 6x4 warm-brown panel in the left half
 int minx=s.w,miny=s.h,maxx=0,maxy=0,count=0;for(int y=s.h/5;y<s.h*4/5;y+=3)for(int x=0;x<s.w*55/100;x+=3){auto c=s.at(x,y);int r=GetRValue(c),g=GetGValue(c),b=GetBValue(c);if(r>65&&r>g*1.15&&g>b*1.25){minx=std::min(minx,x);maxx=std::max(maxx,x);miny=std::min(miny,y);maxy=std::max(maxy,y);count++;}}if(count<300||maxx-minx<220||maxy-miny<150)return false;grid={minx,miny,maxx,maxy};return true;}
void FocusSafetyLoop(){while(g_run){if(!RobloxFocused()){std::scoped_lock lock(keyMutex);heldA=false;heldD=false;if(activeKey)Activate(0);}std::this_thread::sleep_for(25ms);}}
void ChestLoop(){bool latched=false;while(g_run){if(!g_chest||!RobloxFocused()){latched=false;std::this_thread::sleep_for(80ms);continue;}Shot s=Capture();Box g{};bool open=DetectChest(s,g);if(open&&!latched){latched=true;RECT wr{};GetWindowRect(GetForegroundWindow(),&wr);double cw=(g.r-g.l)/6.0,ch=(g.b-g.t)/4.0;POINT old{};GetCursorPos(&old);for(int row=0;row<4&&g_run&&g_chest;row++)for(int col=0;col<6;col++){int x=wr.left+(int)(g.l+(col+.5)*cw),y=wr.top+(int)(g.t+(row+.5)*ch);Click(x,y,true);Click(x,y,false);std::this_thread::sleep_for(20ms);}Key('E',true);Key('E',false);SetCursorPos(old.x,old.y);}if(!open)latched=false;std::this_thread::sleep_for(80ms);} }

void Fill(HDC d,RECT r,COLORREF c){HBRUSH b=CreateSolidBrush(c);FillRect(d,&r,b);DeleteObject(b);}void Text(HDC d,int x,int y,const wchar_t*s,int size,COLORREF c,bool bold=false){HFONT f=CreateFontW(size,0,0,0,bold?FW_BOLD:FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");auto o=SelectObject(d,f);SetBkMode(d,TRANSPARENT);SetTextColor(d,c);TextOutW(d,x,y,s,(int)wcslen(s));SelectObject(d,o);DeleteObject(f);} 
void Toggle(HDC d,int x,int y,bool on){RECT r{x,y,x+46,y+24};Fill(d,r,on?ORANGE:RGB(55,58,70));HBRUSH b=CreateSolidBrush(TEXT);SelectObject(d,b);Ellipse(d,on?x+25:x+3,y+3,on?x+43:x+21,y+21);DeleteObject(b);} 
void Paint(HDC d){RECT rc{};GetClientRect(g_hwnd,&rc);Fill(d,rc,BG);RECT top{0,0,rc.right,55};Fill(d,top,RGB(22,23,29));RECT side{0,55,76,rc.bottom};Fill(d,side,RGB(24,26,33));Text(d,16,17,L"S",26,ORANGE,true);Text(d,40,19,L"SNEWSWARE",15,TEXT,true);Text(d,170,20,L"EMBER",12,ORANGE,true);const wchar_t*nav[]={L"KITS",L"CHEST",L"FISHER",L"SOCD"};for(int i=0;i<4;i++){RECT n{8,82+i*66,68,136+i*66};Fill(d,n,g_tab==i?RGB(73,35,31):RGB(35,38,48));Text(d,15,101+i*66,nav[i],12,g_tab==i?ORANGE:MUTED,true);}int t=g_tab;const wchar_t*title=t==0?L"Kit Automations":t==1?L"Chest Looting":t==2?L"Fisher":L"SOCD Cleaner";const wchar_t*sub=t==0?L"Configure focused BedWars automations.":t==1?L"Detect the 6 x 4 chest and sweep every slot.":t==2?L"Detect and control the fishing minigame.":L"Last strafe input wins. No more movement lock.";Text(d,104,88,title,29,TEXT,true);Text(d,104,126,sub,14,MUTED);RECT line{104,154,610,156};Fill(d,line,RGB(91,43,35));if(t==0){RECT a{104,184,350,350},b{370,184,616,350};Fill(d,a,CARD);Fill(d,b,CARD);Text(d,126,210,L"FISHER",20,TEXT,true);Text(d,126,245,L"Adaptive visual tracking",13,MUTED);Text(d,392,210,L"CHEST",20,TEXT,true);Text(d,392,245,L"24-slot sweep",13,MUTED);}else{RECT card{104,184,650,240};Fill(d,card,CARD);Text(d,122,202,title,16,TEXT,true);Text(d,122,222,L"Master enable / disable",11,MUTED);bool on=t==1?g_chest.load():t==2?g_fisher.load():g_socd.load();Toggle(d,584,199,on);RECT info{104,260,650,430};Fill(d,info,RGB(18,19,24));if(t==1){Text(d,126,282,L"CHECK 80 ms  |  CLICK 20 ms  |  ORDER ROW",13,ORANGE,true);Text(d,126,322,L"Automatically closes with E after the sweep.",14,MUTED);}if(t==2){Text(d,126,282,g_fishingActive?L"TRACKING FISHING UI":L"IDLE — WATCHING EVERY 0.5 s",13,g_fishingActive?GREEN:ORANGE,true);Text(d,126,322,L"Adaptive short-click controller; abort check 0.2 s.",14,MUTED);}if(t==3){Text(d,126,282,L"A / D  — LAST PRESSED PRIORITY",13,ORANGE,true);Text(d,126,322,L"Active only while Roblox is focused.",14,MUTED);}}Text(d,104,rc.bottom-34,L"CTRL + Q  Emergency stop",13,MUTED);}
LRESULT CALLBACK WndProc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_LBUTTONDOWN:{int x=GET_X_LPARAM(l),y=GET_Y_LPARAM(l);if(x<76&&y>=82&&y<346){g_tab=(y-82)/66;InvalidateRect(h,nullptr,FALSE);}else if(x>=570&&x<=650&&y>=184&&y<=245){if(g_tab==1)g_chest=!g_chest;if(g_tab==2)g_fisher=!g_fisher;if(g_tab==3){g_socd=!g_socd;if(!g_socd)ReleaseAutomation();}InvalidateRect(h,nullptr,FALSE);}return 0;}case WM_PAINT:{PAINTSTRUCT p{};HDC d=BeginPaint(h,&p);Paint(d);EndPaint(h,&p);return 0;}case WM_DESTROY:g_run=false;PostQuitMessage(0);return 0;}return DefWindowProc(h,m,w,l);} }
int APIENTRY wWinMain(HINSTANCE hi,HINSTANCE,LPWSTR,int){SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);WNDCLASSEXW wc{sizeof(wc),CS_HREDRAW|CS_VREDRAW,WndProc,0,0,hi,LoadIcon(nullptr,IDI_APPLICATION),LoadCursor(nullptr,IDC_ARROW),(HBRUSH)(COLOR_WINDOW+1),nullptr,kClassName,LoadIcon(nullptr,IDI_APPLICATION)};RegisterClassExW(&wc);g_hwnd=CreateWindowExW(0,kClassName,L"snewsware — ember",WS_OVERLAPPEDWINDOW&~WS_MAXIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,1024,640,nullptr,nullptr,hi,nullptr);BOOL dark=TRUE;DwmSetWindowAttribute(g_hwnd,20,&dark,sizeof(dark));ShowWindow(g_hwnd,SW_SHOW);UpdateWindow(g_hwnd);g_hook=SetWindowsHookExW(WH_KEYBOARD_LL,KeyboardHook,hi,0);std::thread(FisherLoop).detach();std::thread(ChestLoop).detach();std::thread(FocusSafetyLoop).detach();MSG msg{};while(GetMessage(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessage(&msg);}if(g_hook)UnhookWindowsHookEx(g_hook);ReleaseAutomation();return 0;}
